# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/kryozek/Vivado/Vivado/2024.1/platforms/Basys-3-Master.xdc

# Block Designs: bd/FIFO/FIFO.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIFO || ORIG_REF_NAME==FIFO} -quiet] -quiet

# IP: bd/FIFO/ip/FIFO_fifo_generator_0_0_3/FIFO_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIFO_fifo_generator_0_0 || ORIG_REF_NAME==FIFO_fifo_generator_0_0} -quiet] -quiet

# IP: bd/FIFO/ip/FIFO_clk_wiz_1/FIFO_clk_wiz_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIFO_clk_wiz_1 || ORIG_REF_NAME==FIFO_clk_wiz_1} -quiet] -quiet

# XDC: /home/kryozek/Shrine/FPGA/Encryption_Engine/Encryption_Engine.gen/sources_1/bd/FIFO/FIFO_ooc.xdc
