# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kryozek/Shrine/FPGA/Encryption_Engine/Encryption_Engine.srcs/sources_1/bd/FIFO/ip/FIFO_fifo_generator_0_0_3/FIFO_fifo_generator_0_0.xci
# IP: The module: 'FIFO_fifo_generator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kryozek/Shrine/FPGA/Encryption_Engine/Encryption_Engine.gen/sources_1/bd/FIFO/ip/FIFO_fifo_generator_0_0_3/FIFO_fifo_generator_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/kryozek/Shrine/FPGA/Encryption_Engine/Encryption_Engine.gen/sources_1/bd/FIFO/ip/FIFO_fifo_generator_0_0_3/FIFO_fifo_generator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/kryozek/Shrine/FPGA/Encryption_Engine/Encryption_Engine.srcs/sources_1/bd/FIFO/ip/FIFO_fifo_generator_0_0_3/FIFO_fifo_generator_0_0.xci
# IP: The module: 'FIFO_fifo_generator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kryozek/Shrine/FPGA/Encryption_Engine/Encryption_Engine.gen/sources_1/bd/FIFO/ip/FIFO_fifo_generator_0_0_3/FIFO_fifo_generator_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/kryozek/Shrine/FPGA/Encryption_Engine/Encryption_Engine.gen/sources_1/bd/FIFO/ip/FIFO_fifo_generator_0_0_3/FIFO_fifo_generator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
